import type { Project } from '../../interfaces/Objects';

export const projectList: Project[] = [
    {
        id: 1,
        name: 'ToDoList',
        description: 'A simple to-do list with React that runs only in the browser',
        imageURL: '/projects/ToDoList.webp',
        projectURL: 'https://github.com/Davi-1903/ToDoList',
        technologies: ['React', 'Tailwind'],
    },
    {
        id: 2,
        name: 'GoWay',
        description: 'Web design project. Tourism blog.',
        imageURL: '/projects/GoWay.webp',
        projectURL: 'https://github.com/Davi-1903/GoWay',
        technologies: ['HTML', 'CSS', 'JavaScript'],
        team: [
            { id: 1, name: 'Ana Cecilya', url: 'https://github.com/cecilya1' },
            { id: 2, name: 'Ana Clara', url: 'https://github.com/anaclaraa1' },
            { id: 3, name: 'Maria das Graças', url: 'https://github.com/mgdantas1' },
        ],
    },
    {
        id: 3,
        name: 'Dino-IA',
        description: 'Secund project made to study neural networks',
        imageURL: '/projects/Dino-IA.webp',
        projectURL: 'https://github.com/Davi-1903/Dino-IA',
        technologies: ['PyGame', 'NumPy', 'AI'],
    },
    {
        id: 4,
        name: 'EduIA',
        description: 'Intelligent Education Support System.',
        imageURL: '/projects/EduIA.webp',
        projectURL: 'https://github.com/Davi-1903/EduIA',
        technologies: ['React', 'Flask', 'Tailwind', 'MySQL', 'AI'],
        team: [
            { id: 1, name: 'Ana Cecilya', url: 'https://github.com/cecilya1' },
            { id: 2, name: 'Ana Clara', url: 'https://github.com/anaclaraa1' },
            { id: 3, name: 'Maria das Graças', url: 'https://github.com/mgdantas1' },
            { id: 4, name: 'Miguel Tavares', url: 'https://github.com/migueltvrs13' },
        ],
    },
    {
        id: 5,
        name: 'Flappy-Bird-IA',
        description: 'First project mate to study neural networks',
        imageURL: '/projects/Flappy-Bird-IA.webp',
        projectURL: 'https://github.com/Davi-1903/Flappy-Bird-IA',
        technologies: ['PyGame', 'NumPy', 'AI'],
    },
    {
        id: 6,
        name: 'ChatBot',
        description: 'Simple ChatBot with Flask and React',
        imageURL: '/projects/ChatBot.webp',
        projectURL: 'https://github.com/Davi-1903/ChatBot',
        technologies: ['React', 'Flask', 'AI'],
    },
    {
        id: 7,
        name: 'CubeTime',
        description: 'Simple application to learn how to integrate Flask and React',
        imageURL: '/projects/CubeTime.webp',
        projectURL: 'https://github.com/Davi-1903/CubeTime',
        technologies: ['React', 'Flask', 'Tailwind', 'MySQL', 'Docker'],
    },
    {
        id: 8,
        name: 'Expotec-2024',
        description: 'Game developed with pygame for technological exhibition.',
        imageURL: '/projects/Expotec-2024.webp',
        projectURL: 'https://github.com/Davi-1903/Expotec-2024',
        technologies: ['PyGame'],
        team: [
            { id: 1, name: 'Arthur Guilherme', url: 'https://github.com/ArthurGui004' },
            { id: 2, name: 'Pedro Lucas', url: 'https://github.com/Pepeulu' },
            { id: 3, name: 'Guilherme Medeiros', url: 'https://github.com/GuiMeCa162' },
        ],
    },
    {
        id: 9,
        name: 'Termo',
        description: 'A game created on the terminal',
        imageURL: '/projects/Termo.webp',
        projectURL: 'https://github.com/Davi-1903/Termo',
        technologies: ['Python'],
    },
];
